spring.application.name=backend

spring.profiles.active=${SPRING_PROFILES_ACTIVE:local}

# Database settings
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

# JPA settings
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.defer-datasource-initialization=true

# SQL initialization (disabled: no schema.sql/data.sql in resources)
spring.sql.init.mode=always


app.jwt.secret=${JWT_SECRET}
app.jwt.issuer=${JWT_ISSUER}
app.jwt.exp-min=${JWT_EXP_MIN}